# Generated by Django 4.0 on 2021-12-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='date',
            new_name='date_start',
        ),
        migrations.AddField(
            model_name='notes',
            name='date_finish',
            field=models.DateTimeField(default=None),
        ),
    ]
