# Generated by Django 4.0 on 2021-12-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_rename_date_notes_date_start_notes_date_finish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
