# Generated by Django 3.2.9 on 2021-12-08 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_catalog', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_catalog', models.CharField(choices=[('JM', 'Комбинезоны'), ('CS', 'Костюмы'), ('J', 'Куртки')], default=None, max_length=3)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=228)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reima_app.catalog')),
            ],
        ),
    ]
