# Generated by Django 4.0 on 2021-12-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reima_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
