# Generated by Django 3.2.9 on 2021-11-22 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('genre', models.CharField(choices=[('POP', 'Поп-музыка'), ('Rock', 'Рок-музыка'), ('Classic', 'Классическая-музыка'), ('Bluz', 'Блюз'), ('Hip-hop', 'Хип-хоп музыка')], default='POP', max_length=7)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiotek.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiotek.artist')),
            ],
        ),
    ]
